name: Run Tests in Docker

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # docker buildx is necessary (vs docker build) to specify caching
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image with cache
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        tags: pokemon-go-mirror-bot:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        load: true  # necessary so we can run the image locally with `docker run`

    - name: Run pytest inside Docker
      run: |
        docker run --rm pokemon-go-mirror-bot pytest
